spring:
  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB

  datasource:
    url: jdbc:mysql://localhost:3307/novel?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123

  data:
    # Redis
    redis:
      host: 127.0.0.1
      port: 6379
      # password:
      database: 1

  # Spring AMQP 配置
  amqp:
    # 是否开启 Spring AMQP：true-开启 false-不开启
    enabled: true

  rabbitmq:
    host: 127.0.0.1
    port: 5672 # 端口
    virtual-host: /novel # 虚拟主机
    username: efreet # 用户名
    password: 123456 # 密码

  # elasticsearch
  elasticsearch:
    # 是否开启 Elasticsearch 搜索引擎功能：true-开启 false-不开启
    enabled: true
    uris: http://localhost:9200


jwt:
  secret: E66559580A1ADF48CDD928516062F12E
  access-token-expire: 1800
  refresh-token-expire: 604800

aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    region: cn-beijing
    bucket-name: my-awesome-novel